mysite3/blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [
	# /blog/
	url(r'^$', PostLV.as_view(), name='index'),

	# /blog/post/
	url(r'^post/$', PostLV.as_view(), name='post_list'),

	# /blog/post/django-example/
	url(r'^post/(?P<slug>[-\w]+)$', PostDV.as_view(), name='post_detail'),

	# /blog/archive/
	url(r'^archive/$', PostAV.as_view(), name='post_archive'),

	# /blog/2017/
	url(r'^(?P<year>\d{4})/$', PostYAV.as_view(), name='post_year_archive'),

	# /blog/2017/nov/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/$', PostMAV.as_view(), name='post_month_archive'),

	# /blog/2017/nov/10/
	url(r'^(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\d{1,2})/$', PostDAV.as_view(), name='post_day_archive'),

	# /blog/today/
	url(r'^today/$', PostTAV.as_view(), name='post_today_archive'),
]

mysite3/bookmark/urls.py
from django.conf.urls import url
from bookmark.views import BookmarkLV, BookmarkDV

urlpatterns = [
	url(r'^$', BookmarkLV.as_view(), name='index'),
	url(r'^(?P<pk>\d+)/$', BookmarkDV.as_view(), name='detail'),
]

mysite3/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from mysite.views import HomeView

urlpatterns = [
	url(r'', HomeView.as_view(), name='home'),
	url(r'^admin/', admin.site.urls),
	url(r'^bookmark/', include('bookmark.urls', namespace='bookmark')),
	url(r'^blog/', include('blog.urls', namespace='blog')),
]

mysite3/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Post(models.Model):
	title = models.CharField('TITLE', max_length=50)
	slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias') # 디폴트길이 50, allow_unicode : 한글처리
	description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text')
	content = models.TextField('CONTENT')
	create_date = models.DateTimeField('Create Date', auto_now_add=True)
	modify_date = models.DateTimeField('Modify Date', auto_now=True)

	class Meta:
		verbose_name = 'post'
		verbose_name_plural = 'posts'
		db_table = 'my_post'
		ordering = ['-modify_date', ]

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail', args=[self.slug,])

	def get_previous_post(self):
		return self.get_previous_by_modify_date()

	def get_next_post(self):
		return self.get_next_by_modify_date()

mysite3/bookmark/models.py
from django.core.urlresolvers import reverse
from django.db import models

class Bookmark(models.Model):
	title = models.CharField(max_length=100, blank=True)
	url = models.URLField('url', unique=True)

	def get_absolute_url(self):
		return reverse('bookmark:detail', args=[self.id])

	def __str__(self):
		return self.title

mysite3/blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView, DayArchiveView, TodayArchiveView

from blog.models import Post


#--- List View
class PostLV(ListView):
	model = Post
	template_name = 'blog/post_all.html' # 디폴트 post_list.html
	context_object_name = 'posts' # 디폴트 objects_list
	paginate_by = 2


#--- Detail View
class PostDV(DetailView):
	model = Post


#--- Archive View
class PostAV(ArchiveIndexView):
	model = Post
	date_field = 'modify_date'


class PostYAV(YearArchiveView):
	model = Post
	date_field = 'modify_date'
	make_object_list = True


class PostMAV(MonthArchiveView):
	model = Post
	date_field = 'modify_date'


class PostDAV(DayArchiveView):
	model = Post
	date_field = 'modify_date'


class PostTAV(TodayArchiveView):
	model = Post
	date_field = 'modify_date'

mysite3/bookmark/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from bookmark.models import Bookmark

class BookmarkLV(ListView):
	"""
	ListView 디폴트 지정 속성
	1) 컨텍스트 변수 : object_list
	2) 템플릿 파일 : bookmark_list.html (모델명소문자_list.html)
	"""
	model = Bookmark


class BookmarkDV(DetailView):
	"""
	DetailView 디폴트 지정 속성
	1) 컨텍스트 변수 : object (URLConf 에서 pk 파라미터 값을 활용하여 DB 레코드 조회)
	2) 템플릿 파일 : bookmark_detail.html (모델명소문자_detail.html)
	"""
	model = Bookmark

mysite3/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
	template_name = 'home.html' #템플릿 파일이 위치하는 디렉터리는 settings.py 파일의 TEMPLATE_DIRS 항목으로 지정

mysite3/blog/templates/blog/post_all.html
<h1>Blog List</h1>

{% for post in posts %}
	<h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
	{{ post.modify_date|date:"N d, Y" }}
	<p>{{ post.description }}</p>
{% endfor %}

<br>

<div>
	<span>
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">Previous Page</a>
		{% endif %}

		page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">Next Page</a>
		{% endif %}
	</span>
</div>

mysite3/blog/templates/blog/post_archive.html
<h1>Post Archives until {% now "N d, Y"%}</h1>
<ul>
	{% for date in date_list %}
	<li style="display: inline;">
		<a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a>
	</li>
	{% endfor %}
</ul>

<br>

<div>
	<ul>
		{% for post in object_list %}
		<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
		<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>

mysite3/blog/templates/blog/post_archive_day.html
<h1>Post Archive for {{ day|date:"N d, Y" }}</h1>

<div>
	<ul>
		{% for post in object_list %}
			<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
			<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>

mysite3/blog/templates/blog/post_archive_month.html
<h1>Post Archive for {{ month|date:"N, Y" }}</h1>


<div>
	<ul>
		{% for post in object_list %}
			<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
			<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>

mysite3/blog/templates/blog/post_archive_year.html
<h1>Post Archive for {{ year|date:"Y" }}</h1>
<ul>
	{% for date in date_list %}
		<li style="display: inline;">
			<a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a>
		</li>
	{% endfor %}
</ul>

<br>

<div>
	<ul>
		{% for post in object_list %}
			<li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
			<a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a></li>
		{% endfor %}
	</ul>
</div>

mysite3/blog/templates/blog/post_detail.html
<h2>{{ object.title }}</h2>

<p class="other_posts">
	{% if object.get_previous_by_modify_date %}
	<a href="{{ object.get_previous_post.get_absolute_url }}" title="View previous post">&laquo;--{{ object.get_previous_post}}</a>
	{% endif %}

	{% if object.get_next_by_modify_date %}
	<a href="{{ object.get_next_post.get_absolute_url }}" title="View next post">{{ object.get_next_post }} --&raquo;</a>
	{% endif %}
</p>

<p class="date">{{ object.modify_date|date:"j F Y"}}</p>
<br>

<div class="body">
	{{ object.content|linebreaks }}
</div>

mysite3/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Django Bookmark Detail</title>
	</head>
	<body>
		<h1>Bookmark Detail</h1>
		<ul>
			<li>{{ object.title }} : <a href="{{ object.url }}">{{ object.url }}</a></li>
		</ul>
	</body>
</html>

mysite3/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Django Bookmark</title>
	</head>
	<body>
		<div class="content">
			<h1>Bookmark List</h1>
			<ul>
				{% for bookmark in object_list %}
					<li><a href="{{ bookmark.get_absolute_url }}">{{ bookmark.title }}</a></li>
				{% endfor %}
			</ul>

		</div>

	</body>
</html>

mysite3/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}Django Web Programming{% endblock title %}</title>
		{% load staticfiles %}
		<link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">
		<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
	</head>
	<body>
		<div id="header">
			<h2 class="maintitle">Easy&Fast Django Web Programming</h2>
			<h4 class="welcome">Welcome,
				<a href="#">siwa</a>
				<a href="#">Change Password</a>
				<a href="#">Logout</a>
			</h4>
		</div>
		<div id="menu">
			<li><a href="#">Home</a></li>
			<li><a href="#">Bookmark</a></li>
			<li><a href="#">Blog</a></li>
			<li><a href="#">Photo</a></li>

			<li><a href="#">Add&bigtriangledown;</a>
				<ul>
					<li><a href="#">Bookmark</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Photo</a></li>
				</ul>
			</li>

			<li><a href="#">Article</a></li>
			<li><a href="#">Search</a></li>
			<li><a href="#">Admin</a></li>
		</div>

		{% block content %}
		{% endblock %}

		{% block footer %}
		{% endblock %}
	</body>
</html>

mysite3/templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% block content %}
<div id="content">
	This is Content area.
</div>
{% endblock %}

{% block footer %}
<div id="footer">
	This is Footer area.
</div>
{% endblock %}